name: front_end
version: 1.0.0+1
publish_to: none
description: "A Web client for Chat gpt based on Flutter"
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  intl: ^0.17.0
  drift: ^2.4.2
  shared_preferences: ^2.0.17
  retrofit: ^3.3.1
  dio: ^4.0.6
  logger: ^1.1.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_scroll_to_top: ^2.3.0
  lottie: ^2.2.0
  bubble: ^1.2.1
  responsive_framework: ^0.2.0
  card_loading: ^0.2.2
  flutter_dropdown_alert: ^1.0.7
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  animated_text_kit: ^4.2.2
#  katana_model: ^1.3.26

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'
  logger: ^1.1.0
  flutter_launcher_icons: "^0.11.0"




flutter:
  uses-material-design: true
  assets:
    - assets/images/img_bg.jpg
    - assets/icon/icon.png
    - assets/lottie/loading_pacman.zip
    - assets/lottie/robot_error.zip
    - assets/lottie/ask_question.zip
