// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-G036uQI3wV9AN5VSrbGAXrAEZ9wWNo',
    appId: '1:637210700236:web:182e1b0ea4528890965569',
    messagingSenderId: '637210700236',
    projectId: 'youpi-gpt',
    authDomain: 'youpi-gpt.firebaseapp.com',
    storageBucket: 'youpi-gpt.appspot.com',
    measurementId: 'G-FF5N9ZK7KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVV4zNhrHSJcE88LjjiiImS5D20vlBED8',
    appId: '1:637210700236:android:aceb75add8d2d8ad965569',
    messagingSenderId: '637210700236',
    projectId: 'youpi-gpt',
    storageBucket: 'youpi-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmKisyDFp525OUO4degTlkynfE9ni72Tk',
    appId: '1:637210700236:ios:17d931ce7e72bd7d965569',
    messagingSenderId: '637210700236',
    projectId: 'youpi-gpt',
    storageBucket: 'youpi-gpt.appspot.com',
    iosClientId: '637210700236-ai4ijesbkq9d65qs49t0bst6cf6e5bm9.apps.googleusercontent.com',
    iosBundleId: 'tg.tmye.frontEnd',
  );
}
